#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    name: root
    password: root

#mybaits-plus配置
plusconfig:
  #父包路径
  parent: com.zgl.generatechs
  #模块名
  moduleName:
  #生成文件输出目录，不填默认位当前项目src/main/code目录
  outputDir:
  #实体是否生成swagger注解
  swaggerOpen: true
  #实体是否为lombok模型
  lombokModel: true
  #是否覆盖已有文件
  fileOverride: true
  #生成类的作者签名
  author: zgl
  #需要包含的表名，多个表面使用英文逗号间隔
  include: t_course_info,user_info
  #需要去除的表前缀，不去除配置空值
  tablePrefix: t_
  #需要去除的字段前缀，不去除配置空值
  fieldPrefix:
